// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"ffxiv.anid.dev/internal/aws"
	"ffxiv.anid.dev/internal/config"
	"ffxiv.anid.dev/internal/manager"
	"ffxiv.anid.dev/internal/server"
)

// Injectors from wire.go:

func InitializeServer(c *config.Config) (*server.Server, error) {
	session := aws.NewSession()
	dynamoDBAPI := aws.NewDynamoClient(session)
	dynamoDBTableName := c.TableName
	masterPK := c.MasterPK
	tasksManager := &manager.TasksManager{
		DynSvc:   dynamoDBAPI,
		Table:    dynamoDBTableName,
		MasterPK: masterPK,
	}
	serverServer, err := server.NewServer(tasksManager)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
